title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: "https://limeQueen.github.io/index.html"
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

remote_theme : brianmaierjr/long-haul

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: https://github.com/limeQueen
  twitter: 
  facebook: 
  email: suplin.baek@gmail.com
  linkedin: 

google_analytics: ""

disqus:
    shortname: limeQueen
